server:
  port: 8989

spring:
  application:
    name: service-miya
  zipkin:
    base-url: http://192.168.1.149:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/