server:
  port: 8762

spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/linyi4843/springCloudConfig
          searchPaths: config
          username:
          password:
      label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    metadata-map:
#      user.name: admin
#      user.password: admin

