server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
# 8761   8666
spring:
  application:
    name: eurka-server
  security:
    user:
      name: admin
      password: admin

